<a href="https://colab.research.google.com/github/riddhikarlekar17/Data_Science_Lab_SE_A__26/blob/main/DS_PRAC_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create 3x3 matrix
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Compute determinant
det = np.linalg.det(A)

print("Matrix:\n", A)
print("Determinant:", det)

Matrix:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Determinant: 0.9999999999999964


In [2]:
import numpy as np

# Create same matrix
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Find inverse
A_inv = np.linalg.inv(A)

print("Matrix:\n", A)
print("Inverse:\n", A_inv)

Matrix:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Inverse:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [3]:
import numpy as np

# Coefficient matrix
A = np.array([[2, 3],
              [4, 5]])

# Constant matrix
B = np.array([10, 20])

# Solve equations
solution = np.linalg.solve(A, B)

print("Solution (x, y):", solution)

Solution (x, y): [5. 0.]
