<a href="https://colab.research.google.com/github/riddhikarlekar17/Data_Science_Lab_SE_A__26/blob/main/Practical_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Understanding NumPy for Matrix Manipulations

NumPy is a powerful library for numerical operations in Python, especially for working with arrays and matrices. Let's start by creating a sample matrix.

In [1]:
import numpy as np

# Create a sample 3x3 matrix
matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original Matrix A:")
print(matrix_a)

Original Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2. Calculating the Determinant of a Matrix

The determinant is a scalar value that can be computed from the elements of a square matrix. It provides important information about the matrix, such as whether it is invertible. In NumPy, you can use `np.linalg.det()`.

In [2]:
import numpy as np

# For a singular matrix (determinant is 0 or very close to 0)
matrix_singular = np.array([
    [1, 2],
    [2, 4]
])

det_singular = np.linalg.det(matrix_singular)
print(f"Determinant of singular matrix: {det_singular:.4f}")

# For a non-singular matrix
matrix_b = np.array([
    [1, 2],
    [3, 4]
])

det_b = np.linalg.det(matrix_b)
print(f"Determinant of matrix B: {det_b:.4f}")

# For the initial matrix_a (should be singular too, since row 3 is linearly dependent on row 2 and 1)
det_a = np.linalg.det(matrix_a)
print(f"Determinant of Matrix A: {det_a:.4f}")

Determinant of singular matrix: 0.0000
Determinant of matrix B: -2.0000
Determinant of Matrix A: 0.0000


### 3. Finding the Inverse of a Matrix

The inverse of a square matrix $A$, denoted $A^{-1}$, is a matrix such that when multiplied by $A$, it yields the identity matrix. A matrix must be non-singular (i.e., have a non-zero determinant) to have an inverse. NumPy's `np.linalg.inv()` function is used for this.

Let's use `matrix_b` for this example, as `matrix_a` and `matrix_singular` are singular and do not have an inverse.

In [3]:
import numpy as np

matrix_b = np.array([
    [1, 2],
    [3, 4]
])

# Calculate the inverse of matrix_b
inverse_b = np.linalg.inv(matrix_b)
print("Inverse of Matrix B:")
print(inverse_b)

# Verify by multiplying the matrix by its inverse (should yield identity matrix)
identity_check = np.dot(matrix_b, inverse_b)
print("\nMatrix B multiplied by its inverse (should be identity matrix):")
print(identity_check)

Inverse of Matrix B:
[[-2.   1. ]
 [ 1.5 -0.5]]

Matrix B multiplied by its inverse (should be identity matrix):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


### 4. Solving a System of Linear Equations Using Matrix Methods

A system of linear equations can be represented in matrix form as $Ax = B$, where $A$ is the coefficient matrix, $x$ is the variable vector, and $B$ is the constant vector. We can solve for $x$ using `np.linalg.solve()`.

Consider the system:
$x + 2y = 5$
$3x + 4y = 11$

In [4]:
import numpy as np

# Coefficient matrix A
A = np.array([
    [1, 2],
    [3, 4]
])

# Constant vector B
B = np.array([5, 11])

# Solve the system of equations
x = np.linalg.solve(A, B)

print("Solution for x and y:")
print(f"x = {x[0]:.2f}")
print(f"y = {x[1]:.2f}")

# Verify the solution
print("\nVerification:")
print(f"1*{x[0]:.2f} + 2*{x[1]:.2f} = {1*x[0] + 2*x[1]:.2f} (should be 5)")
print(f"3*{x[0]:.2f} + 4*{x[1]:.2f} = {3*x[0] + 4*x[1]:.2f} (should be 11)")

Solution for x and y:
x = 1.00
y = 2.00

Verification:
1*1.00 + 2*2.00 = 5.00 (should be 5)
3*1.00 + 4*2.00 = 11.00 (should be 11)
